### ISSUE TITLE
No old versions of LINQPad driver

### ISSUE THREAD

**Issue by maciejczekajbitech** [SolutionsDesign/LINQPadDriver#5]
Releases section should have all possible versions not only version 4.2 and 5.0.
I'm looking for version 5.3 but there is only 5.0 and on LLBL site is only 5.5.
Could you please add a release for each new version. I'll build the driver for myself but It would be nice to have the entire history.

**Comment by FransBouma** [comment]
When you log in, under My Account -> v5.3 -> Extras section there's a linqpad driver build for v5.3. So the release history is available to you. 

To build from source use: https://github.com/SolutionsDesign/LINQPadDriver/tree/0b83305fded6cd830c52c9f90c9ca3bcfd887128

**Comment by maciejczekajbitech** [comment]
Thanks!
