### ISSUE TITLE
v5.6 can't be installed to LinqPad

### ISSUE THREAD

**Issue by snekbaev** [SolutionsDesign/LINQPadDriver#7]
Hi,

`header.xml` `MainAssembly` needs to have a proper version set. For now edited manually.

Thank you!

P.S.: on a side note: why "Enable ORM profiler" checkbox is greyed out?

**Comment by FransBouma** [comment]
Thanks for the heads up regarding header.xml, I used the one in the deploy folders so I overlooked the one in the source folder! :) 

regarding the orm profiler checkbox: it has to determine where the interceptor folder is, so it first checks if the `.opsnapshot` extension is registered. If so, it checks via the icon registration in the registry the folder of the interceptor. 

I think this is indeed something that needs some work, as in: it might be better if the user simply specifies the interceptor dll to use, and if it's specified, it's enabled. We'll see what we can do about that.

**Comment by snekbaev** [comment]
Yeah, I do have v2.0.1 profiler installed and it was even open. It would be great to make this work consistently :) What would be the easiest way to make it work meanwhile?

Thank you!

**Comment by FransBouma** [comment]
I'll see if I can get this fixed later this afternoon :)

**Comment by snekbaev** [comment]
Nice :) Would appreciate if v.5.5 will be updated too. Haven't upgraded to 5.6 yet :)

**Comment by FransBouma** [comment]
Will do :)

**Comment by FransBouma** [comment]
Binaries on the site for v5.5 and v5.6 are now updated to reflect the new controls in the connection pane. Source here is updated for v5.6. This should fix the issue :)
